name: Deploy Generated File via FTP

on:
  push:
    branches:
      - main # Or the branch you want this to run on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment (if needed for your script)
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run script to generate database
      run: |
        make db-build

    - name: PHP tests
      run: |
        make php-test

    - name: Deploy database files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # port: ${{ secrets.FTP_PORT }} # Optional, remove if using default 21
        local-dir: './db/yocal/' # The local directory where your generated file is
        server-dir: '/httpdocs/wp/wp-content/uploads/yocal/' # The remote path on your FTP server

    - name: Deploy API files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # port: ${{ secrets.FTP_PORT }} # Optional, remove if using default 21
        local-dir: './api-php/' # The local directory
        server-dir: '/httpdocs/api-php/' # The remote path
        exclude: |
          **/.htaccess
          **/*.sh
